package taskruntime

import (
	"context"
	"testing"
	"time"

	agentcontracts "github.com/GrayCodeAI/eagle/agent"
)

// --- SpawnAgent tests ---

func TestSpawnAgent_NilFn(t *testing.T) {
	r := New()
	id := r.SpawnAgent(context.Background(), "t1", agentcontracts.SpawnRequest{}, nil)
	if id != "" {
		t.Errorf("expected empty id for nil fn, got %q", id)
	}
}

func TestSpawnAgent_EmptyID_AutoGenerated(t *testing.T) {
	r := New()
	id := r.SpawnAgent(context.Background(), "", agentcontracts.SpawnRequest{Prompt: "hi"},
		func(_ context.Context, _ agentcontracts.SpawnRequest) (agentcontracts.SpawnResult, error) {
			return agentcontracts.SpawnResult{Output: "ok"}, nil
		})
	if id != "agent-1" {
		t.Errorf("expected agent-1, got %q", id)
	}
}

func TestSpawnAgent_ErrorResult(t *testing.T) {
	r := New()
	id := r.SpawnAgent(context.Background(), "err1", agentcontracts.SpawnRequest{Prompt: "hi"},
		func(_ context.Context, _ agentcontracts.SpawnRequest) (agentcontracts.SpawnResult, error) {
			return agentcontracts.SpawnResult{}, context.DeadlineExceeded
		})
	waitForTask(r, id, 2*time.Second)
	task, ok := r.Get(id)
	if !ok {
		t.Fatal("missing task")
	}
	if task.Status != StatusFailed {
		t.Errorf("status=%s, want %s", task.Status, StatusFailed)
	}
	if task.Error != context.DeadlineExceeded.Error() {
		t.Errorf("error=%q, want %q", task.Error, context.DeadlineExceeded.Error())
	}
}

func TestSpawnAgent_CanceledContext_Killed(t *testing.T) {
	r := New()
	ctx, cancel := context.WithCancel(context.Background())
	id := r.SpawnAgent(ctx, "kill1", agentcontracts.SpawnRequest{Prompt: "x"},
		func(ctx context.Context, _ agentcontracts.SpawnRequest) (agentcontracts.SpawnResult, error) {
			<-ctx.Done()
			// Return nil error to trigger StatusKilled path
			return agentcontracts.SpawnResult{}, nil
		})
	cancel()
	waitForTask(r, id, 2*time.Second)
	task, ok := r.Get(id)
	if !ok {
		t.Fatal("missing task")
	}
	if task.Status != StatusKilled {
		t.Errorf("status=%s, want %s", task.Status, StatusKilled)
	}
	if task.Error != "killed" {
		t.Errorf("error=%q, want %q", task.Error, "killed")
	}
}

func TestSpawnAgent_EmptyOutput_UsesSummary(t *testing.T) {
	r := New()
	id := r.SpawnAgent(context.Background(), "sum1", agentcontracts.SpawnRequest{Prompt: "hi"},
		func(_ context.Context, _ agentcontracts.SpawnRequest) (agentcontracts.SpawnResult, error) {
			return agentcontracts.SpawnResult{Summary: "summary text"}, nil
		})
	waitForTask(r, id, 2*time.Second)
	task, ok := r.Get(id)
	if !ok {
		t.Fatal("missing task")
	}
	if task.Output != "summary text" {
		t.Errorf("output=%q, want %q", task.Output, "summary text")
	}
}

// --- Get tests ---

func TestGet_RunningTask(t *testing.T) {
	r := New()
	id := r.SpawnAgent(context.Background(), "run1", agentcontracts.SpawnRequest{Prompt: "x"},
		func(ctx context.Context, _ agentcontracts.SpawnRequest) (agentcontracts.SpawnResult, error) {
			<-ctx.Done()
			return agentcontracts.SpawnResult{}, ctx.Err()
		})
	defer r.Kill(id)
	// Give it a moment to start
	time.Sleep(50 * time.Millisecond)
	task, ok := r.Get(id)
	if !ok {
		t.Fatal("expected to find running task")
	}
	if task.Status != StatusRunning {
		t.Errorf("status=%s, want %s", task.Status, StatusRunning)
	}
}

func TestGet_NonExistent(t *testing.T) {
	r := New()
	_, ok := r.Get("nonexistent")
	if ok {
		t.Error("expected false for non-existent task")
	}
}

// --- IsRunning tests ---

func TestIsRunning_NonExistent(t *testing.T) {
	r := New()
	if r.IsRunning("nonexistent") {
		t.Error("expected false for non-existent task")
	}
}

// --- Elapsed tests ---

func TestElapsed_RunningTask(t *testing.T) {
	r := New()
	id := r.SpawnAgent(context.Background(), "elapsed1", agentcontracts.SpawnRequest{Prompt: "x"},
		func(ctx context.Context, _ agentcontracts.SpawnRequest) (agentcontracts.SpawnResult, error) {
			<-ctx.Done()
			return agentcontracts.SpawnResult{}, ctx.Err()
		})
	defer r.Kill(id)
	time.Sleep(50 * time.Millisecond)
	elapsed := r.Elapsed(id)
	if elapsed <= 0 {
		t.Error("expected positive elapsed time for running task")
	}
}

func TestElapsed_NonExistent(t *testing.T) {
	r := New()
	elapsed := r.Elapsed("nonexistent")
	if elapsed != 0 {
		t.Errorf("expected 0 for non-existent task, got %v", elapsed)
	}
}

// --- Kill tests ---

func TestKill_NonExistent(t *testing.T) {
	r := New()
	err := r.Kill("nonexistent")
	if err == nil {
		t.Error("expected error for killing non-existent task")
	}
}

// --- Wait tests ---

func TestWait_EmptyRegistry(t *testing.T) {
	r := New()
	tasks := r.Wait(100 * time.Millisecond)
	if len(tasks) != 0 {
		t.Errorf("expected 0 tasks, got %d", len(tasks))
	}
}

func TestWait_TimeoutWithRunningTask(t *testing.T) {
	r := New()
	r.SpawnAgent(context.Background(), "wait1", agentcontracts.SpawnRequest{Prompt: "x"},
		func(ctx context.Context, _ agentcontracts.SpawnRequest) (agentcontracts.SpawnResult, error) {
			<-ctx.Done()
			return agentcontracts.SpawnResult{}, ctx.Err()
		})
	tasks := r.Wait(50 * time.Millisecond)
	// Task is still running, should get 0 completed tasks
	if len(tasks) != 0 {
		t.Errorf("expected 0 completed tasks (timeout), got %d", len(tasks))
	}
}

func TestWait_CompletesAfterTimeout(t *testing.T) {
	r := New()
	r.SpawnAgent(context.Background(), "wait2", agentcontracts.SpawnRequest{Prompt: "x"},
		func(_ context.Context, _ agentcontracts.SpawnRequest) (agentcontracts.SpawnResult, error) {
			return agentcontracts.SpawnResult{Output: "done"}, nil
		})
	// Wait long enough for the task to complete
	tasks := r.Wait(2 * time.Second)
	if len(tasks) != 1 {
		t.Errorf("expected 1 completed task, got %d", len(tasks))
	}
}

// --- CollectCompleted tests ---

func TestCollectCompleted_Empty(t *testing.T) {
	r := New()
	tasks := r.CollectCompleted()
	if len(tasks) != 0 {
		t.Errorf("expected 0 tasks, got %d", len(tasks))
	}
}

func TestCollectCompleted_ClearsDone(t *testing.T) {
	r := New()
	id := r.SpawnAgent(context.Background(), "collect1", agentcontracts.SpawnRequest{Prompt: "x"},
		func(_ context.Context, _ agentcontracts.SpawnRequest) (agentcontracts.SpawnResult, error) {
			return agentcontracts.SpawnResult{Output: "ok"}, nil
		})
	waitForTask(r, id, 2*time.Second)

	// First collect
	tasks := r.CollectCompleted()
	if len(tasks) != 1 {
		t.Fatalf("expected 1 task, got %d", len(tasks))
	}
	// Second collect should be empty
	tasks = r.CollectCompleted()
	if len(tasks) != 0 {
		t.Errorf("expected 0 tasks after clear, got %d", len(tasks))
	}
}

// --- PendingCount and HasPending tests ---

func TestPendingCount_Empty(t *testing.T) {
	r := New()
	if r.PendingCount() != 0 {
		t.Error("expected 0 pending tasks")
	}
}

func TestPendingCount_WithRunning(t *testing.T) {
	r := New()
	id := r.SpawnAgent(context.Background(), "pend1", agentcontracts.SpawnRequest{Prompt: "x"},
		func(ctx context.Context, _ agentcontracts.SpawnRequest) (agentcontracts.SpawnResult, error) {
			<-ctx.Done()
			return agentcontracts.SpawnResult{}, ctx.Err()
		})
	defer r.Kill(id)
	time.Sleep(50 * time.Millisecond)
	if r.PendingCount() != 1 {
		t.Errorf("expected 1 pending task, got %d", r.PendingCount())
	}
}

func TestHasPending_Empty(t *testing.T) {
	r := New()
	if r.HasPending() {
		t.Error("expected no pending tasks")
	}
}

func TestHasPending_WithRunning(t *testing.T) {
	r := New()
	id := r.SpawnAgent(context.Background(), "pend2", agentcontracts.SpawnRequest{Prompt: "x"},
		func(ctx context.Context, _ agentcontracts.SpawnRequest) (agentcontracts.SpawnResult, error) {
			<-ctx.Done()
			return agentcontracts.SpawnResult{}, ctx.Err()
		})
	defer r.Kill(id)
	time.Sleep(50 * time.Millisecond)
	if !r.HasPending() {
		t.Error("expected pending tasks")
	}
}

// --- RegisterExternal tests ---

func TestRegisterExternal_EmptyID(t *testing.T) {
	r := New()
	r.RegisterExternal("", KindShell, "test", func() {})
	// Should be a no-op
	if r.PendingCount() != 0 {
		t.Error("expected 0 tasks after registering empty id")
	}
}

func TestRegisterExternal_Valid(t *testing.T) {
	r := New()
	cancel := context.CancelFunc(func() {})
	r.RegisterExternal("ext1", KindShell, "shell task", cancel)
	if r.PendingCount() != 1 {
		t.Errorf("expected 1 task, got %d", r.PendingCount())
	}
	task, ok := r.Get("ext1")
	if !ok {
		t.Fatal("expected to find external task")
	}
	if task.Kind != KindShell {
		t.Errorf("kind=%s, want %s", task.Kind, KindShell)
	}
	if task.Prompt != "shell task" {
		t.Errorf("prompt=%q, want %q", task.Prompt, "shell task")
	}
}

// --- FinishExternal tests ---

func TestFinishExternal_RunningTask(t *testing.T) {
	r := New()
	r.RegisterExternal("ext2", KindShell, "shell task", func() {})
	r.FinishExternal("ext2", StatusCompleted, "output", "")
	task, ok := r.Get("ext2")
	if !ok {
		t.Fatal("expected to find finished task")
	}
	if task.Status != StatusCompleted {
		t.Errorf("status=%s, want %s", task.Status, StatusCompleted)
	}
	if task.Output != "output" {
		t.Errorf("output=%q, want %q", task.Output, "output")
	}
	if r.PendingCount() != 0 {
		t.Error("expected 0 pending tasks after finish")
	}
}

func TestFinishExternal_DoneTask(t *testing.T) {
	r := New()
	r.RegisterExternal("ext3", KindShell, "shell task", func() {})
	r.FinishExternal("ext3", StatusCompleted, "first", "")
	r.FinishExternal("ext3", StatusFailed, "second", "error")
	task, ok := r.Get("ext3")
	if !ok {
		t.Fatal("expected to find task")
	}
	if task.Status != StatusFailed {
		t.Errorf("status=%s, want %s", task.Status, StatusFailed)
	}
	if task.Output != "second" {
		t.Errorf("output=%q, want %q", task.Output, "second")
	}
	if task.Error != "error" {
		t.Errorf("error=%q, want %q", task.Error, "error")
	}
}

func TestFinishExternal_NonExistent(t *testing.T) {
	r := New()
	r.FinishExternal("nonexistent", StatusCompleted, "output", "")
	// Should be a no-op
}

// --- AppendOutput tests ---

func TestAppendOutput_RunningTask(t *testing.T) {
	r := New()
	r.RegisterExternal("out1", KindShell, "shell task", func() {})
	r.AppendOutput("out1", "hello ")
	r.AppendOutput("out1", "world")
	task, ok := r.Get("out1")
	if !ok {
		t.Fatal("expected to find task")
	}
	if task.Output != "hello world" {
		t.Errorf("output=%q, want %q", task.Output, "hello world")
	}
}

func TestAppendOutput_DoneTask(t *testing.T) {
	r := New()
	r.RegisterExternal("out2", KindShell, "shell task", func() {})
	r.FinishExternal("out2", StatusCompleted, "initial", "")
	r.AppendOutput("out2", " appended")
	task, ok := r.Get("out2")
	if !ok {
		t.Fatal("expected to find task")
	}
	if task.Output != "initial appended" {
		t.Errorf("output=%q, want %q", task.Output, "initial appended")
	}
}

func TestAppendOutput_NonExistent(t *testing.T) {
	r := New()
	r.AppendOutput("nonexistent", "data")
	// Should be a no-op
}

func TestAppendOutput_Truncation(t *testing.T) {
	r := New()
	r.RegisterExternal("out3", KindShell, "shell task", func() {})
	// Append more than max (200,000 bytes)
	large := make([]byte, 250000)
	for i := range large {
		large[i] = 'x'
	}
	r.AppendOutput("out3", string(large))
	task, ok := r.Get("out3")
	if !ok {
		t.Fatal("expected to find task")
	}
	// Truncation keeps last 200,000 bytes + "...(truncated)\n" prefix (15 bytes) = 200,015
	expectedLen := len("...(truncated)\n") + 200000
	if len(task.Output) != expectedLen {
		t.Errorf("output length=%d, expected %d", len(task.Output), expectedLen)
	}
	if !contains(task.Output, "...(truncated)") {
		t.Error("expected truncation marker")
	}
}

// --- WaitIDs tests ---

func TestWaitIDs_EmptyIDs(t *testing.T) {
	r := New()
	tasks := r.WaitIDs([]string{}, 100*time.Millisecond)
	// Should fall back to Wait
	if len(tasks) != 0 {
		t.Errorf("expected 0 tasks, got %d", len(tasks))
	}
}

func TestWaitIDs_WithRunningTasks(t *testing.T) {
	r := New()
	id1 := r.SpawnAgent(context.Background(), "wid1", agentcontracts.SpawnRequest{Prompt: "x"},
		func(_ context.Context, _ agentcontracts.SpawnRequest) (agentcontracts.SpawnResult, error) {
			return agentcontracts.SpawnResult{Output: "done1"}, nil
		})
	id2 := r.SpawnAgent(context.Background(), "wid2", agentcontracts.SpawnRequest{Prompt: "y"},
		func(_ context.Context, _ agentcontracts.SpawnRequest) (agentcontracts.SpawnResult, error) {
			return agentcontracts.SpawnResult{Output: "done2"}, nil
		})
	tasks := r.WaitIDs([]string{id1, id2}, 2*time.Second)
	if len(tasks) != 2 {
		t.Errorf("expected 2 tasks, got %d", len(tasks))
	}
}

func TestWaitIDs_TimeoutWithRunningTask(t *testing.T) {
	r := New()
	id := r.SpawnAgent(context.Background(), "wid3", agentcontracts.SpawnRequest{Prompt: "x"},
		func(ctx context.Context, _ agentcontracts.SpawnRequest) (agentcontracts.SpawnResult, error) {
			<-ctx.Done()
			return agentcontracts.SpawnResult{}, ctx.Err()
		})
	defer r.Kill(id)
	tasks := r.WaitIDs([]string{id}, 50*time.Millisecond)
	// Task is still running, should get the running task
	if len(tasks) != 1 {
		t.Errorf("expected 1 task (running), got %d", len(tasks))
	}
}

func TestWaitIDs_NonExistentIDs(t *testing.T) {
	r := New()
	tasks := r.WaitIDs([]string{"nonexistent1", "nonexistent2"}, 100*time.Millisecond)
	// Non-existent IDs should return empty results
	if len(tasks) != 0 {
		t.Errorf("expected 0 tasks for non-existent IDs, got %d", len(tasks))
	}
}

// --- List tests ---

func TestList_Empty(t *testing.T) {
	r := New()
	tasks := r.List()
	if len(tasks) != 0 {
		t.Errorf("expected 0 tasks, got %d", len(tasks))
	}
}

func TestList_WithRunningAndDone(t *testing.T) {
	r := New()
	id1 := r.SpawnAgent(context.Background(), "list1", agentcontracts.SpawnRequest{Prompt: "x"},
		func(_ context.Context, _ agentcontracts.SpawnRequest) (agentcontracts.SpawnResult, error) {
			return agentcontracts.SpawnResult{Output: "done"}, nil
		})
	waitForTask(r, id1, 2*time.Second)

	id2 := r.SpawnAgent(context.Background(), "list2", agentcontracts.SpawnRequest{Prompt: "y"},
		func(ctx context.Context, _ agentcontracts.SpawnRequest) (agentcontracts.SpawnResult, error) {
			<-ctx.Done()
			return agentcontracts.SpawnResult{}, ctx.Err()
		})
	defer r.Kill(id2)
	time.Sleep(50 * time.Millisecond)

	tasks := r.List()
	if len(tasks) != 2 {
		t.Errorf("expected 2 tasks, got %d", len(tasks))
	}
}

// --- Default registry test ---

func TestDefaultRegistry(t *testing.T) {
	if Default == nil {
		t.Error("expected non-nil Default registry")
	}
	if Default.PendingCount() != 0 {
		t.Error("expected 0 pending tasks on Default registry")
	}
}

// --- Helper functions ---

func waitForTask(r *Registry, id string, timeout time.Duration) {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if !r.IsRunning(id) {
			return
		}
		time.Sleep(10 * time.Millisecond)
	}
}

func contains(s, substr string) bool {
	return len(s) >= len(substr) && (s == substr || len(s) > 0 && containsHelper(s, substr))
}

func containsHelper(s, substr string) bool {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return true
		}
	}
	return false
}
