// Package planning implements tree-search backtracking over candidate states
// (Yao et al. ToT, NeurIPS 2023 arXiv 2305.10601; Zhou et al. LATS, ICLR 2024
// arXiv 2310.04406). A value function scores each state, the search expands the
// best candidates breadth-first, and branches that dead-end (no expansion) are
// pruned so the search backtracks to the next best alternative.
package planning

import (
	"context"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/GrayCodeAI/graycode-cli/internal/types"
)

// Expander generates the candidate next states reachable from a state. An
// empty result means the state is a leaf (dead-end for that branch).
type Expander interface {
	Expand(state string) []string
}

// Scorer is the value function: higher is better.
type Scorer interface {
	Score(state string) float64
}

// Node is one state in the search tree.
type Node struct {
	State    string
	Score    float64
	Depth    int
	Children []*Node
}

// BeamSearch explores the tree from root breadth-first, keeping the top
// beamWidth candidates per depth, and backtracks by pruning branches that
// dead-end (produce no children). It returns the highest-scoring leaf reached
// within maxDepth, or nil if nothing expands.
//
// It is deterministic given deterministic Expander/Scorer implementations.
func BeamSearch(root string, expand Expander, score Scorer, beamWidth, maxDepth int) *Node {
	if maxDepth <= 0 {
		maxDepth = 8
	}
	if beamWidth <= 0 {
		beamWidth = 3
	}

	rootNode := &Node{State: root, Score: score.Score(root), Depth: 0}
	frontier := []*Node{rootNode}
	best := rootNode

	for depth := 1; depth <= maxDepth && len(frontier) > 0; depth++ {
		var next []*Node
		for _, n := range frontier {
			children := expand.Expand(n.State)
			if len(children) == 0 {
				continue // dead-end: prune this branch (backtrack)
			}
			for _, c := range children {
				cn := &Node{State: c, Score: score.Score(c), Depth: depth}
				n.Children = append(n.Children, cn)
				next = append(next, cn)
			}
		}
		if len(next) == 0 {
			break
		}
		// Keep only the top beamWidth by score (stable tie-break by first seen).
		sort.SliceStable(next, func(i, j int) bool { return next[i].Score > next[j].Score })
		if len(next) > beamWidth {
			next = next[:beamWidth]
		}
		frontier = next
		// The best reachable state is the top scorer in the deepest viable
		// frontier (dead-ends already pruned above). Overwrite, not max: a
		// shallower high-score node that later dead-ends must be superseded by
		// the deeper reachable leaf.
		best = frontier[0]
	}

	return best
}

// ModelExpander asks an LLM provider to generate the candidate next states
// reachable from a state. It implements Expander so BeamSearch can be driven by
// real model outputs in the live agent loop.
type ModelExpander struct {
	Provider types.ChatProvider
	Model    string
	Prompt   string // instructions for expansion, e.g. "suggest the next plan step"
}

// Expand returns candidate next states generated by the model.
func (e *ModelExpander) Expand(state string) []string {
	resp, err := e.Provider.Chat(context.Background(), []types.GraycodeRouterMessage{
		{Role: "system", Content: e.Prompt},
		{Role: "user", Content: state},
	}, types.ChatOptions{Model: e.Model, MaxTokens: 512})
	if err != nil || resp == nil {
		return nil
	}
	return splitCandidates(resp.Content)
}

// ModelScorer asks an LLM provider to score a state on a 0..1 scale. It
// implements Scorer.
type ModelScorer struct {
	Provider types.ChatProvider
	Model    string
	Prompt   string // instructions for scoring, e.g. "rate this plan step 0..1"
}

// Score returns the model's 0..1 value for a state.
func (s *ModelScorer) Score(state string) float64 {
	resp, err := s.Provider.Chat(context.Background(), []types.GraycodeRouterMessage{
		{Role: "system", Content: s.Prompt},
		{Role: "user", Content: state},
	}, types.ChatOptions{Model: s.Model, MaxTokens: 16})
	if err != nil || resp == nil {
		return 0
	}
	return parseScore(resp.Content)
}

// splitCandidates splits a model response into candidate states, one per line
// or numbered item, trimmed and de-duplicated.
func splitCandidates(content string) []string {
	var out []string
	seen := map[string]bool{}
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		line = strings.TrimLeft(line, "-*•0123456789.) ")
		line = strings.TrimSpace(line)
		if line == "" || seen[line] {
			continue
		}
		seen[line] = true
		out = append(out, line)
	}
	return out
}

// parseScore extracts a 0..1 score from a model response, defaulting to 0.
func parseScore(content string) float64 {
	for _, tok := range strings.Fields(strings.TrimSpace(content)) {
		if f, err := strconv.ParseFloat(strings.Trim(tok, ",.:;%"), 64); err == nil {
			if f > 1 {
				f = f / 100.0
			}
			if f < 0 {
				f = 0
			}
			if f > 1 {
				f = 1
			}
			return f
		}
	}
	return 0
}

// PlanWithBeamSearch runs a model-driven BeamSearch over a root plan state and
// returns the best reachable plan (or the root when nothing expands). It is the
// integration point that feeds real model outputs into the tree search.
func PlanWithBeamSearch(
	provider types.ChatProvider,
	model, root, expandPrompt, scorePrompt string,
	beamWidth, maxDepth int,
) (string, error) {
	if provider == nil {
		return "", fmt.Errorf("planning: no LLM provider for beam search")
	}
	expander := &ModelExpander{Provider: provider, Model: model, Prompt: expandPrompt}
	scorer := &ModelScorer{Provider: provider, Model: model, Prompt: scorePrompt}
	best := BeamSearch(root, expander, scorer, beamWidth, maxDepth)
	if best == nil {
		return root, nil
	}
	return best.State, nil
}
