package gitworktree

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestCreate_NotAGitRepo(t *testing.T) {
	tmpDir := t.TempDir()
	_, _, err := Create(context.Background(), tmpDir, "test-branch")
	if err == nil {
		t.Fatal("expected error for non-git directory")
	}
	if !strings.Contains(err.Error(), "not a git repository") {
		t.Errorf("error = %q, want to contain 'not a git repository'", err.Error())
	}
}

func TestCreate_WithGitRepo(t *testing.T) {
	// Create a temp git repo
	tmpDir := t.TempDir()

	// Initialize a git repo
	runGit(t, tmpDir, "init")
	runGit(t, tmpDir, "config", "user.email", "test@test.com")
	runGit(t, tmpDir, "config", "user.name", "Test")
	// Create initial commit
	if err := os.WriteFile(filepath.Join(tmpDir, "README.md"), []byte("# Test"), 0644); err != nil {
		t.Fatal(err)
	}
	runGit(t, tmpDir, "add", ".")
	runGit(t, tmpDir, "commit", "-m", "initial")

	// Create worktree
	path, cleanup, err := Create(context.Background(), tmpDir, "test-worktree")
	if err != nil {
		t.Fatalf("Create error: %v", err)
	}
	defer cleanup()

	if path == "" {
		t.Error("expected non-empty path")
	}
	if _, err := os.Stat(path); os.IsNotExist(err) {
		t.Error("worktree path should exist")
	}
}

func TestCreate_EmptyBranch_AutoGenerated(t *testing.T) {
	tmpDir := t.TempDir()
	runGit(t, tmpDir, "init")
	runGit(t, tmpDir, "config", "user.email", "test@test.com")
	runGit(t, tmpDir, "config", "user.name", "Test")
	if err := os.WriteFile(filepath.Join(tmpDir, "README.md"), []byte("# Test"), 0644); err != nil {
		t.Fatal(err)
	}
	runGit(t, tmpDir, "add", ".")
	runGit(t, tmpDir, "commit", "-m", "initial")

	// Create worktree with empty branch name (should auto-generate)
	path, cleanup, err := Create(context.Background(), tmpDir, "")
	if err != nil {
		t.Fatalf("Create error: %v", err)
	}
	defer cleanup()

	if path == "" {
		t.Error("expected non-empty path")
	}
}

func TestCreate_Cleanup(t *testing.T) {
	tmpDir := t.TempDir()
	runGit(t, tmpDir, "init")
	runGit(t, tmpDir, "config", "user.email", "test@test.com")
	runGit(t, tmpDir, "config", "user.name", "Test")
	if err := os.WriteFile(filepath.Join(tmpDir, "README.md"), []byte("# Test"), 0644); err != nil {
		t.Fatal(err)
	}
	runGit(t, tmpDir, "add", ".")
	runGit(t, tmpDir, "commit", "-m", "initial")

	path, cleanup, err := Create(context.Background(), tmpDir, "cleanup-test")
	if err != nil {
		t.Fatalf("Create error: %v", err)
	}

	// Verify path exists
	if _, err := os.Stat(path); os.IsNotExist(err) {
		t.Fatal("worktree path should exist before cleanup")
	}

	// Run cleanup
	cleanup()

	// Verify path is removed
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Error("worktree path should be removed after cleanup")
	}
}

func TestCreate_CleanupWithTimeout(t *testing.T) {
	tmpDir := t.TempDir()
	runGit(t, tmpDir, "init")
	runGit(t, tmpDir, "config", "user.email", "test@test.com")
	runGit(t, tmpDir, "config", "user.name", "Test")
	if err := os.WriteFile(filepath.Join(tmpDir, "README.md"), []byte("# Test"), 0644); err != nil {
		t.Fatal(err)
	}
	runGit(t, tmpDir, "add", ".")
	runGit(t, tmpDir, "commit", "-m", "initial")

	_, cleanup, err := Create(context.Background(), tmpDir, "timeout-test")
	if err != nil {
		t.Fatalf("Create error: %v", err)
	}

	// Cleanup should complete within reasonable time
	done := make(chan struct{})
	go func() {
		cleanup()
		close(done)
	}()

	select {
	case <-done:
		// Good
	case <-time.After(35 * time.Second):
		t.Error("cleanup took too long (should timeout at 30s)")
	}
}

// --- Helper functions ---

func runGit(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.CommandContext(context.Background(), "git", args...)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %s failed: %v\n%s", strings.Join(args, " "), err, string(out))
	}
}
